### ISSUE TITLE
Tagesplan, Depot, links/rechts fehlt

### ISSUE THREAD

**Issue by Martin-Jonasse** [TIXI24/requirements#39]
![linksrechts](https://cloud.githubusercontent.com/assets/4991526/17517316/39bfea38-5e43-11e6-920b-2dfc58fe102e.PNG)

Noch nicht ausprogrammiert.

**Comment by Martin-Jonasse** [comment]
Patrizia wünscht sich drag & drop, was besser zu der bestehende Software passt.

Plausibilität:
- Stackoverflow: how to drag a shape along a given path?
- See http://jsfiddle.net/fuzic/kKLtH

**Comment by ruemon** [comment]
Falls dies möglich ist, würde ich eine solche Lösung begrüssen.
24.10.2016/Monika

**Comment by Martin-Jonasse** [comment]
Dies wurde wie folgt gelöst:
1. Verschieben einer Fahrt an der Stelle einer Boxenstopp, schiebt der Boxenstopp automatisch nach links (früher), oder nach rechts (später).
2. Desgleichen wenn ein neue Fahrt angelegt wird.
3. Verchieben von Boxenstopps ist möglich, führt aber zu eine Fehlermeldung (Hinweis).
4. Dies ist dokumentiert in AnwendungsfallTagesplanBoxenstopp.docx.
