### ISSUE TITLE
Vormund, erfassen/editieren für Rolle Dispo erlauben

### ISSUE THREAD

**Issue by ruemon** [TIXI24/requirements#44]
Momentan für Rolle Manager ausgelegt.

Anforderung: TIXI ZUG, Monika Rüegg, auch für Rolle Dispo.
![vormund](https://cloud.githubusercontent.com/assets/16398634/18089753/cbcd79c0-6ec1-11e6-94dc-9778e8ab7d8e.PNG)

**Comment by ruemon** [comment]
**Label**
•	Verwaltung
•	Wichtig
•	Nicht dringend

**Comment by Martin-Jonasse** [comment]
Implementiert für Rollen DISPO, MANAGER and ADMIN:
![screenshot 2016-10-14 13 18 50](https://cloud.githubusercontent.com/assets/4991526/19386023/4bcb9b16-9212-11e6-96fc-2a9730dfd43f.png)
