### ISSUE TITLE
Tagesplan, Dauer Schichtwechsel (Depot)

### ISSUE THREAD

**Issue by ruemon** [TIXI24/requirements#49]
Ausgangslage: 
Für den Schichtwechsel ist auf 10 Minuten eingestellt. 

Anforderung: 
Für einen sorgfältige Übergabe der Fahrzeuge bei Schichtwechsel (Fahrerwechsel) sind mindestens 20 Minuten notwendig. Die Dauer des Schichtwechsels ist daher auf 20 Minuten anzupassen.

Labels: wichtig, nicht dringend

Monika Rüegg, TIXI ZUG

**Comment by Martin-Jonasse** [comment]
Die Code wurde entsprechend angepasst. Es ist zu beachten, dass Schichtwechsel gespeicherte Objekte sind (mit 10 Minuten). Der neue Wert (20 Minuten) wird erst nach "Optimieren" richtig dargestellt.

Screenshot (neu):
![screenshot 2016-10-11 18 33 43](https://cloud.githubusercontent.com/assets/4991526/19279574/3cac7966-8fe2-11e6-8218-3305e4db36a7.png)
