### ISSUE TITLE
Auftragerfassung/Fahrauftrag: Adresse-Zusatz bei "Zuhause"-Funktion integrieren

### ISSUE THREAD

**Issue by ruemon** [TIXI24/requirements#60]
Szenario:
Die Funktion „Zuhause“-Adresse übernimmt die ‚Strasse‘ auf den Auftrag. Dies ist nicht ausreichend, da wichtige Hinweise im ‚Adress-Zusatz‘ (z.B. Alterszentrum Herti) hinterlegt ist. Diese Information ist für den Fahrer wie auch für die Disponentin sehr wichtig zur Orientierung. 
   
Anforderungen:
Beim Anklicken der "Zuhause"-Funktion soll nebst der Adresse auch das Feld Adress-Zusatz angezeigt und auf den Fahrauftrag übernommen werden  

![grafik](https://cloud.githubusercontent.com/assets/16398634/26211747/90fb2f9a-3bf3-11e7-9c91-8883d49582fe.png)

Quelle:
TIXIZUG, Monika Rüegg
Pendenz aus Sitzungsprotokoll Punkt 2.1

**Comment by ruemon** [comment]
@Martin-Jonasse - Bitte Prio 3 Label setzen

**Comment by Martin-Jonasse** [comment]
Implemented as of build 1411, hash 9ddd9ad
